import {
  App,
  daemonDefaultConfig,
  daemonInvalidDefaultConfig,
  daemonOverview,
  daemonOverviewDevicesUnavailable,
  daemonOverviewDirtyMetadataStrings,
  daemonOverviewInterfaceDevices,
  daemonOverviewInvalidBooleanConfig,
  daemonOverviewInvalidConfig,
  daemonOverviewInvalidEnumMetadataValues,
  daemonOverviewInvalidFloatConfig,
  daemonOverviewInvalidIpConfig,
  daemonOverviewInvalidNumberRangeConfig,
  daemonOverviewInvalidStringConfig,
  daemonOverviewListItemWithoutId,
  daemonOverviewMetadataUnavailable,
  daemonOverviewMissingMetadataId,
  daemonOverviewNumericEnum,
  daemonOverviewReserved,
  daemonOverviewRunning,
  deferredResponse,
  describe,
  expect,
  fireEvent,
  installAppTestHooks,
  it,
  openDaemon,
  overview,
  profileCatalog,
  render,
  screen,
  stubFetch,
  vi,
  waitFor,
  within
} from "./test/appTestHarness";

describe("TRex Daemon", () => {
  installAppTestHooks();

  it("posts daemon TRex start with the dialog timeout and YAML preview", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:start_trex",
          host: "10.0.0.10",
          port: 8090,
          action: "start",
          result: 17,
          sequence: 17,
          user: "unit",
          timeout_seconds: 55,
          config_filename: "unit",
          config_uploaded: true,
          files_path: "/tmp/trex-files",
          trex_cmd_options: { cfg: "/tmp/trex-files/unit" },
          audit_record: {
            action: "start",
            created_at: "2026-06-08T00:00:00+00:00",
            config_path: "/tmp/trex-files/unit",
            version_name: "20260608T000000000000Z-start-aaaaaaaaaaaa.yaml",
            version_sha256: "a".repeat(64),
            sequence: 17,
            config_filename: "unit",
            files_path: "/tmp/trex-files",
            user: "unit",
            host: "10.0.0.10",
            daemon_port: 8090
          },
          audit_written: true,
          blocker: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewRunning })
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "local:daemon_config_audit",
          root_path: "/var/log/trex/config-versions",
          audit_path: "/var/log/trex/config-versions/audit.jsonl",
          limit: 50,
          records: [
            {
              action: "start",
              created_at: "2026-06-08T00:00:00+00:00",
              config_path: "/tmp/trex-files/unit",
              version_name: "20260608T000000000000Z-start-aaaaaaaaaaaa.yaml",
              version_sha256: "a".repeat(64),
              sequence: 17,
              config_filename: "unit",
              files_path: "/tmp/trex-files",
              user: "unit",
              host: "10.0.0.10",
              daemon_port: 8090
            }
          ],
          truncated: false,
          skipped_lines: 0
        })
      });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    await waitFor(() => expect(screen.getByLabelText("Port limit")).toHaveValue("2"));
    fireEvent.change(screen.getByLabelText("Port limit"), { target: { value: "6" } });
    fireEvent.change(screen.getByLabelText("Start timeout"), { target: { value: "55" } });
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    const startCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/trex/start");
    expect(startCall).toBeDefined();
    const startBody = JSON.parse(String(startCall?.[1]?.body));
    expect(startBody.confirmation).toBe("start-trex");
    expect(startBody.timeout_seconds).toBe(55);
    expect(startBody.config_content).toContain("### Config file generated by TRex Stateless GUI ###");
    expect(startBody.config_content).toContain("port_limit: 6");
    expect(window.confirm).toHaveBeenCalledWith("Start TRex through the daemon with the current config preview?");
    fireEvent.click(screen.getByRole("tab", { name: "Log" }));
    const daemonLog = screen.getByRole("region", { name: "TRex daemon log" });
    expect(daemonLog).toHaveClass("daemon-readonly-code", "daemon-readonly-code--log");
    expect(daemonLog).toHaveAttribute("tabindex", "0");
    await waitFor(() => expect(daemonLog).toHaveTextContent("Config was uploaded successfully"));
    expect(daemonLog).toHaveTextContent("Starting TRex... (timeout is 55 sec)");
    expect(daemonLog).toHaveTextContent("TRex run sequence: 17");
    expect(daemonLog).toHaveTextContent("TRex was started successfully");
    await waitFor(() => expect(daemonLog).toHaveTextContent("TRex status: TRex is Running"));
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/config/audit?limit=50"));
    fireEvent.click(screen.getByRole("tab", { name: "Audit" }));
    expect(screen.getAllByText("Start").length).toBeGreaterThan(0);
    expect(screen.getByText("seq 17")).toBeInTheDocument();
  });

  it("exports daemon config preview without starting TRex", async () => {
    const writeText = vi.fn().mockResolvedValue(undefined);
    Object.defineProperty(navigator, "clipboard", {
      configurable: true,
      value: { writeText }
    });
    Object.defineProperty(window.URL, "createObjectURL", {
      configurable: true,
      value: vi.fn(() => "blob:daemon-config")
    });
    Object.defineProperty(window.URL, "revokeObjectURL", {
      configurable: true,
      value: vi.fn()
    });
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    expect(screen.getAllByText("Valid preview").length).toBeGreaterThan(0);
    expect(screen.getByText("Target: /etc/trex_cfg.yaml")).toBeInTheDocument();
    const yamlPreview = screen.getByRole("region", { name: "Generated TRex YAML preview" });
    expect(yamlPreview).toHaveClass("daemon-readonly-code", "daemon-readonly-code--yaml");
    expect(yamlPreview).toHaveAttribute("tabindex", "0");
    expect(yamlPreview.querySelector("code")).toHaveClass("daemon-readonly-code-content");
    expect(yamlPreview).toHaveTextContent("port_limit: 2");
    expect(screen.getByRole("region", { name: "TRex config editor fields" })).toBeInTheDocument();

    const daemonDialog = screen.getByRole("dialog", { name: "TRex Daemon" });
    for (const tabId of ["config", "versions", "audit", "log"]) {
      expect(daemonDialog.querySelector(`#daemon-panel-${tabId}`)).not.toBeNull();
    }

    fireEvent.click(screen.getByRole("button", { name: "Copy preview" }));
    await waitFor(() => expect(writeText).toHaveBeenCalledWith(expect.stringContaining("port_limit: 2")));
    await waitFor(() => expect(screen.getByText("Preview copied")).toBeInTheDocument());

    fireEvent.click(screen.getByRole("button", { name: "Download preview" }));
    expect(window.URL.createObjectURL).toHaveBeenCalled();
    expect(screen.getByText("Preview downloaded trex-daemon-preview.yaml")).toBeInTheDocument();
    expect(fetchMock.mock.calls.some(([url]) => url === "/api/system/daemon/trex/start")).toBe(false);

    const configTab = screen.getByRole("tab", { name: "Config" });
    const versionsTab = screen.getByRole("tab", { name: "Versions" });
    configTab.focus();
    fireEvent.keyDown(configTab, { key: "ArrowRight" });
    expect(versionsTab).toHaveFocus();
    expect(versionsTab).toHaveAttribute("aria-selected", "true");
    expect(daemonDialog.querySelector("#daemon-panel-config")).toHaveAttribute("hidden");
  });

  it("labels daemon config upload failures like the original daemon dialog", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: false,
          source: "daemon:push_file",
          host: "10.0.0.10",
          port: 8090,
          action: "start",
          result: false,
          sequence: null,
          user: "unit",
          timeout_seconds: 40,
          config_filename: "unit",
          config_uploaded: false,
          files_path: null,
          trex_cmd_options: null,
          blocker: "daemon_config_upload_failed",
          error: "TRex Daemon IO error"
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    expect(screen.getByText("Config upload to TRex host failed: TRex Daemon IO error")).toBeInTheDocument();
    expect(screen.queryByText("Unable to start TRex: TRex Daemon IO error")).not.toBeInTheDocument();
  });

  it("does not post daemon TRex start when confirmation is canceled", async () => {
    vi.spyOn(window, "confirm").mockReturnValue(false);
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    expect(window.confirm).toHaveBeenCalledWith("Start TRex through the daemon with the current config preview?");
    expect(fetchMock).not.toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything());
  });

  it("keeps original daemon controls disabled while a TRex command is pending", async () => {
    const startResponse = deferredResponse({
      ok: true,
      source: "daemon:start_trex",
      host: "10.0.0.10",
      port: 8090,
      action: "start",
      result: 19,
      sequence: 19,
      user: "unit",
      timeout_seconds: 40,
      config_filename: "unit",
      config_uploaded: true,
      files_path: "/tmp/trex-files",
      trex_cmd_options: { cfg: "/tmp/trex-files/unit" },
      blocker: null
    });
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockReturnValueOnce(startResponse.promise)
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewRunning })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    expect(screen.getByRole("button", { name: "Connect" })).toBeDisabled();
    expect(screen.getByLabelText("Start timeout")).not.toBeDisabled();
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    expect(screen.getByRole("button", { name: "Load default config" })).toBeDisabled();
    expect(screen.getByLabelText("Start timeout")).toBeDisabled();
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
    expect(screen.getByRole("button", { name: "Stop" })).toBeDisabled();

    startResponse.resolve();
    fireEvent.click(screen.getByRole("tab", { name: "Log" }));
    const daemonLog = screen.getByRole("region", { name: "TRex daemon log" });
    await waitFor(() => expect(daemonLog).toHaveTextContent("TRex run sequence: 19"));
  });

  it("does not build daemon config controls from metadata fields without ids", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewMissingMetadataId })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:start_trex",
          host: "10.0.0.10",
          port: 8090,
          action: "start",
          result: 1,
          sequence: 1,
          user: "unit",
          config_filename: "unit",
          config_uploaded: true,
          files_path: "/tmp/trex-files",
          trex_cmd_options: { cfg: "/tmp/trex-files/unit" },
          blocker: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewMissingMetadataId })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    expect(screen.queryByLabelText("Port limit")).not.toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    const startCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/trex/start");
    const startBody = JSON.parse(String(startCall?.[1]?.body));
    expect(startBody.config_content).toBe("- port_limit: 2\n");
  });

  it("does not build daemon config controls from dirty metadata strings", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewDirtyMetadataStrings });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    expect(screen.queryByLabelText("Port limit")).not.toBeInTheDocument();
    expect(screen.queryByLabelText("Enable ZMQ publisher")).not.toBeInTheDocument();
  });

  it("does not build daemon config controls from invalid enum metadata values", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInvalidEnumMetadataValues });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    expect(screen.queryByLabelText("Mode")).not.toBeInTheDocument();
  });

  it("preserves numeric daemon enum values when generating config", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewNumericEnum })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:start_trex",
          host: "10.0.0.10",
          port: 8090,
          action: "start",
          result: 3,
          sequence: 3,
          user: "unit",
          config_filename: "unit",
          config_uploaded: true,
          files_path: "/tmp/trex-files",
          trex_cmd_options: { cfg: "/tmp/trex-files/unit" },
          blocker: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewNumericEnum })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    expect(screen.getByLabelText("Mode")).toHaveValue("0");
    fireEvent.change(screen.getByLabelText("Mode"), { target: { value: "1" } });
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    const startCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/trex/start");
    const startBody = JSON.parse(String(startCall?.[1]?.body));
    expect(startBody.config_content).toContain("mode: 2");
    expect(startBody.config_content).not.toContain('mode: "2"');
  });

  it("keeps daemon config editing when only devices info is unavailable", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewDevicesUnavailable });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    expect(screen.getByLabelText("Port limit")).toHaveValue("2");
    expect(screen.queryByText(/custom config usage will not be available/)).not.toBeInTheDocument();
  });

  it("disables daemon config editing when config metadata is unavailable", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewMetadataUnavailable });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    await waitFor(() => expect(screen.getByText("TRex config edit")).toBeInTheDocument());
    expect(screen.getByText("TRex config edit").closest("details")).toHaveAttribute("aria-disabled", "true");
    expect(screen.getByText("TRex config edit").closest("details")).not.toHaveAttribute("open");
    expect(screen.queryByLabelText("Port limit")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Load default config" })).toBeDisabled();
  });

  it("accepts real daemon LIST item metadata without item ids", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewListItemWithoutId })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:start_trex",
          host: "10.0.0.10",
          port: 8090,
          action: "start",
          result: 2,
          sequence: 2,
          user: "unit",
          config_filename: "unit",
          config_uploaded: true,
          files_path: "/tmp/trex-files",
          trex_cmd_options: { cfg: "/tmp/trex-files/unit" },
          blocker: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewListItemWithoutId })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    await waitFor(() => expect(screen.getByLabelText("Interface")).toHaveValue("0000:02:00.0"));
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    const startCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/trex/start");
    const startBody = JSON.parse(String(startCall?.[1]?.body));
    expect(startBody.config_content).toContain("interfaces:");
    expect(startBody.config_content).toContain("- '0000:02:00.0'");
    expect(startBody.config_content).not.toContain("- 0000:02:00.0");
    expect(startBody.config_content).not.toContain("Interface:");
  });

  it("quotes short PCI interface strings before daemon TRex start", async () => {
    const daemonOverviewShortPciInterface = {
      ...daemonOverviewListItemWithoutId,
      config: {
        ...daemonOverviewListItemWithoutId.config,
        content: "- interfaces:\n  - 03:00.0\n"
      }
    };
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewShortPciInterface })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:start_trex",
          host: "10.0.0.10",
          port: 8090,
          action: "start",
          result: 3,
          sequence: 3,
          user: "unit",
          config_filename: "unit",
          config_uploaded: true,
          files_path: "/tmp/trex-files",
          trex_cmd_options: { cfg: "/tmp/trex-files/unit" },
          blocker: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewShortPciInterface })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    await waitFor(() => expect(screen.getByLabelText("Interface")).toHaveValue("03:00.0"));
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    const startCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/trex/start");
    const startBody = JSON.parse(String(startCall?.[1]?.body));
    expect(startBody.config_content).toContain("- '03:00.0'");
    expect(startBody.config_content).not.toContain("- 03:00.0");
  });

  it("selects daemon interface values from real devices info", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInterfaceDevices })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:start_trex",
          host: "10.0.0.10",
          port: 8090,
          action: "start",
          result: 4,
          sequence: 4,
          user: "unit",
          config_filename: "unit",
          config_uploaded: true,
          files_path: "/tmp/trex-files",
          trex_cmd_options: { cfg: "/tmp/trex-files/unit" },
          blocker: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInterfaceDevices })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    expect(screen.getByLabelText("Select Interface")).toHaveValue("0000:02:00.0");
    fireEvent.change(screen.getByLabelText("Select Interface"), { target: { value: "0000:02:00.1" } });
    expect(screen.getByLabelText("Interface")).toHaveValue("0000:02:00.1");
    fireEvent.click(screen.getByRole("button", { name: "Start" }));

    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/trex/start", expect.anything()));
    const startCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/trex/start");
    const startBody = JSON.parse(String(startCall?.[1]?.body));
    expect(startBody.config_content).toContain("- '0000:02:00.1'");
    expect(startBody.config_content).not.toContain("- 0000:02:00.1");
    expect(startBody.config_content).not.toContain("ens2f1");
  });

  it("loads daemon default config from the original dialog command", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonDefaultConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Load default config" }));

    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon/config/default"));
  });

  it("manages daemon config versions from the daemon dialog", async () => {
    const version = {
      name: "20260607T120000000000Z-manual-8d1a6db7c5b1.yaml",
      path: "/var/log/trex/config-versions/20260607T120000000000Z-manual-8d1a6db7c5b1.yaml",
      created_at: "2026-06-07T12:00:00.000000+00:00",
      modified_time: "2026-06-07T12:00:00.000000+00:00",
      size_bytes: 14,
      sha256: "8d1a6db7c5b174f9687a131ce254f2b9ad36a1b6af2adfa91edc46111e2ce540",
      source: "manual",
      note: "webui preview",
      config_path: "/etc/trex_cfg.yaml",
      host: "10.0.0.10",
      daemon_port: 8090
    };
    const beforeVersion = {
      ...version,
      name: "20260607T121000000000Z-restore_before-111111111111.yaml",
      path: "/var/log/trex/config-versions/20260607T121000000000Z-restore_before-111111111111.yaml",
      source: "restore_before",
      note: `before restore ${version.name}`
    };
    const versionsPayload = {
      ok: true,
      source: "local:daemon_config_versions",
      root_path: "/var/log/trex/config-versions",
      limit: 50,
      versions: [version],
      blocker: null,
      error: null
    };
    const auditPayload = {
      ok: true,
      source: "local:daemon_config_audit",
      root_path: "/var/log/trex/config-versions",
      audit_path: "/var/log/trex/config-versions/audit.jsonl",
      limit: 50,
      records: [
        {
          action: "restore",
          created_at: "2026-06-07T12:10:00.000000+00:00",
          config_path: "/etc/trex_cfg.yaml",
          restored_name: version.name,
          restored_sha256: version.sha256,
          before_name: beforeVersion.name,
          host: "10.0.0.10",
          daemon_port: 8090
        }
      ],
      truncated: false,
      skipped_lines: 0,
      blocker: null,
      error: null
    };
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({ ok: true, json: async () => versionsPayload })
      .mockResolvedValueOnce({ ok: true, json: async () => auditPayload })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "local:daemon_config_version_diff",
          root_path: "/var/log/trex/config-versions",
          name: version.name,
          version,
          diff: "--- old\n+++ current\n-port_limit: 2\n+port_limit: 4\n",
          truncated: false,
          compared_to: "request",
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "local:daemon_config_version_load",
          root_path: "/var/log/trex/config-versions",
          name: version.name,
          version,
          content: "port_limit: 4\n",
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "local:daemon_config_version_save",
          root_path: "/var/log/trex/config-versions",
          saved: true,
          version,
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => versionsPayload })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "local:daemon_config_version_restore",
          root_path: "/var/log/trex/config-versions",
          name: version.name,
          restored: true,
          config_path: "/etc/trex_cfg.yaml",
          before_version: beforeVersion,
          restored_version: version,
          audit_record: {
            action: "restore",
            restored_name: version.name,
            before_name: beforeVersion.name
          },
          audit_written: true,
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({ ok: true, json: async () => ({ ...versionsPayload, versions: [beforeVersion, version] }) })
      .mockResolvedValueOnce({ ok: true, json: async () => auditPayload });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    fireEvent.click(screen.getByRole("tab", { name: "Versions" }));
    let versionsPanel = screen.getByLabelText("TRex config versions");
    fireEvent.click(within(versionsPanel).getByRole("button", { name: "Refresh" }));
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/config/versions?limit=50"));
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/config/audit?limit=50"));
    await waitFor(() => expect(within(versionsPanel).getByLabelText("Config version")).toHaveValue(version.name));
    fireEvent.click(screen.getByRole("tab", { name: "Audit" }));
    const auditPanel = screen.getByLabelText("TRex config audit");
    await waitFor(() => expect(auditPanel).toBeInTheDocument());
    await waitFor(() => expect(within(auditPanel).getByText(version.sha256.slice(0, 12))).toBeInTheDocument());
    fireEvent.click(screen.getByRole("tab", { name: "Versions" }));
    versionsPanel = screen.getByLabelText("TRex config versions");
    await waitFor(() => expect(within(versionsPanel).getByRole("button", { name: "Diff" })).not.toBeDisabled());

    fireEvent.click(within(versionsPanel).getByRole("button", { name: "Diff" }));
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/config/versions/diff", expect.anything()));
    await waitFor(() =>
      expect(within(versionsPanel).getByText((content) => content.includes("+port_limit: 4"))).toBeInTheDocument()
    );

    await waitFor(() => expect(within(versionsPanel).getByRole("button", { name: "Load" })).not.toBeDisabled());
    fireEvent.click(within(versionsPanel).getByRole("button", { name: "Load" }));
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/config/versions/load", expect.anything()));
    await waitFor(() => expect(within(versionsPanel).getByText(`Loaded ${version.name}`)).toBeInTheDocument());

    await waitFor(() => expect(within(versionsPanel).getByRole("button", { name: "Save" })).not.toBeDisabled());
    fireEvent.click(within(versionsPanel).getByRole("button", { name: "Save" }));
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/config/versions/save", expect.anything()));
    const saveCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/config/versions/save");
    const saveBody = JSON.parse(String(saveCall?.[1]?.body));
    expect(saveBody.config_content).toContain("port_limit: 4");
    await waitFor(() => expect(within(versionsPanel).getByText(`Saved ${version.name}`)).toBeInTheDocument());

    await waitFor(() => expect(within(versionsPanel).getByRole("button", { name: "Restore" })).not.toBeDisabled());
    fireEvent.click(within(versionsPanel).getByRole("button", { name: "Restore" }));
    expect(window.confirm).toHaveBeenCalledWith(
      `Restore config version ${version.name} to /etc/trex_cfg.yaml? Current config will be backed up first.`
    );
    await waitFor(() => expect(fetchMock).toHaveBeenCalledWith("/api/system/daemon/config/versions/restore", expect.anything()));
    const restoreCall = fetchMock.mock.calls.find(([url]) => url === "/api/system/daemon/config/versions/restore");
    const restoreBody = JSON.parse(String(restoreCall?.[1]?.body));
    expect(restoreBody).toEqual({ name: version.name, confirmation: "restore-config" });
    await waitFor(() =>
      expect(within(versionsPanel).getByText(`Restored ${version.name}; backup ${beforeVersion.name}`)).toBeInTheDocument()
    );
    await waitFor(() => expect(within(versionsPanel).getAllByText("Restore").length).toBeGreaterThan(0));
    await waitFor(() => expect(within(versionsPanel).getAllByText(version.sha256.slice(0, 12)).length).toBeGreaterThan(0));
  });

  it("logs and blocks malformed daemon default config YAML", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonInvalidDefaultConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Load default config" }));

    await waitFor(() =>
      expect(screen.getAllByText(/Unable to parse received default config YAML/).length).toBeGreaterThan(0)
    );
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
    expect(screen.getAllByText(/errors in config/).length).toBeGreaterThan(0);
  });

  it("disables daemon start when the generated config is invalid", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInvalidConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    await waitFor(() => expect(screen.getByText(/errors in config/)).toBeInTheDocument());
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
  });

  it("rejects malformed daemon FLOAT config values before start", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInvalidFloatConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    await waitFor(() => expect(screen.getAllByText(/cannot be parsed as FLOAT/).length).toBeGreaterThan(0));
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
  });

  it("rejects daemon NUMBER config values outside the original integer range", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInvalidNumberRangeConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    await waitFor(() => expect(screen.getAllByText(/cannot be parsed as NUMBER/).length).toBeGreaterThan(0));
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
  });

  it("rejects daemon BOOLEAN config values that are YAML strings", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInvalidBooleanConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    await waitFor(() => expect(screen.getAllByText(/cannot be parsed as BOOLEAN/).length).toBeGreaterThan(0));
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
  });

  it("rejects malformed daemon IP config values before start", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInvalidIpConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    await waitFor(() => expect(screen.getAllByText(/cannot be parsed as IP/).length).toBeGreaterThan(0));
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
  });

  it("rejects daemon STRING config values that are not YAML strings", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewInvalidStringConfig });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    await waitFor(() => expect(screen.getAllByText(/cannot be parsed as STRING/).length).toBeGreaterThan(0));
    expect(screen.getByRole("button", { name: "Start" })).toBeDisabled();
  });

  it("filters daemon start timeout to digits like the original dialog", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));

    fireEvent.change(screen.getByLabelText("Start timeout"), { target: { value: "5a5s" } });

    expect(screen.getByLabelText("Start timeout")).toHaveValue("55");
  });

  it("posts daemon TRex stop from the original dialog command", async () => {
    vi.spyOn(window, "confirm").mockReturnValue(true);
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:force_trex_kill",
          host: "10.0.0.10",
          port: 8090,
          action: "stop",
          stopped: true,
          result: true,
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Stop" }));

    await waitFor(() =>
      expect(fetchMock).toHaveBeenCalledWith(
        "/api/system/daemon/trex/stop",
        expect.objectContaining({
          body: JSON.stringify({ confirmation: "stop-trex" }),
          method: "POST"
        })
      )
    );
    expect(window.confirm).toHaveBeenCalledWith("Stop TRex through the daemon on the configured host?");
    expect(screen.getByText("TRex stopped successfully")).toBeInTheDocument();
  });

  it("logs daemon stop false result as not running like the original dialog", async () => {
    vi.spyOn(window, "confirm").mockReturnValue(true);
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:force_trex_kill",
          host: "10.0.0.10",
          port: 8090,
          action: "stop",
          stopped: false,
          result: false,
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({ ok: true, json: async () => overview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Stop" }));

    await waitFor(() => expect(screen.getAllByText("TRex is not running").length).toBeGreaterThan(0));
    expect(screen.queryByText(/Unable to stop TRex/)).not.toBeInTheDocument();
  });

  it("does not post daemon TRex stop when confirmation is canceled", async () => {
    vi.spyOn(window, "confirm").mockReturnValue(false);
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Stop" }));

    expect(window.confirm).toHaveBeenCalledWith("Stop TRex through the daemon on the configured host?");
    expect(fetchMock).not.toHaveBeenCalledWith("/api/system/daemon/trex/stop", expect.anything());
  });

  it("controls daemon reservation through the original daemon dialog", async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce({ ok: true, json: async () => overview })
      .mockResolvedValueOnce({ ok: true, json: async () => profileCatalog })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:reserve_trex",
          host: "10.0.0.10",
          port: 8090,
          action: "reserve",
          user: "root",
          reserved: true,
          result: true,
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverviewReserved })
      .mockResolvedValueOnce({
        ok: true,
        json: async () => ({
          ok: true,
          source: "daemon:cancel_reservation",
          host: "10.0.0.10",
          port: 8090,
          action: "cancel",
          user: "root",
          canceled: true,
          result: true,
          blocker: null,
          error: null
        })
      })
      .mockResolvedValueOnce({ ok: true, json: async () => daemonOverview });
    stubFetch(fetchMock);

    render(<App />);

    await waitFor(() => expect(screen.getByText("Connected to TRex RPC")).toBeInTheDocument());
    openDaemon();
    await waitFor(() => expect(fetchMock).toHaveBeenLastCalledWith("/api/system/daemon"));
    fireEvent.click(screen.getByRole("button", { name: "Reserve" }));

    await waitFor(() =>
      expect(fetchMock).toHaveBeenCalledWith(
        "/api/system/daemon/trex/reservation/reserve",
        expect.objectContaining({
          method: "POST",
          body: JSON.stringify({ user: null })
        })
      )
    );
    await waitFor(() => expect(screen.getByText("Reservation: Reserved")).toBeInTheDocument());
    expect(screen.getAllByText("TRex reservation was acquired successfully").length).toBeGreaterThan(0);
    fireEvent.click(screen.getByRole("button", { name: "Cancel" }));

    await waitFor(() =>
      expect(fetchMock).toHaveBeenCalledWith(
        "/api/system/daemon/trex/reservation/cancel",
        expect.objectContaining({
          method: "POST",
          body: JSON.stringify({ user: null })
        })
      )
    );
    expect(screen.getAllByText("TRex reservation was canceled successfully").length).toBeGreaterThan(0);
  });
});
