from __future__ import annotations

import base64
from typing import Any

import yaml

from app.trex.workbench_layout import (
    workbench_mpls_label_field_name,
    workbench_mpls_stack,
    workbench_mpls_tc_field_name,
    workbench_mpls_ttl_field_name,
    workbench_outer_ether_type,
    workbench_vlan_cfi_field_name,
    workbench_vlan_id_field_name,
    workbench_vlan_priority_field_name,
    workbench_vlan_tag_count,
    workbench_vlan_tpid_field_name,
    workbench_vlan_tpid_override_field_name,
)
from app.trex.workbench_protocol import (
    workbench_has_arp,
    workbench_has_icmp,
    workbench_has_l3,
    workbench_ip_version,
)
from app.trex.workbench_values import PROFILE_DEFAULT_GTPU_EXTENSION_TYPE_UDP_PORT


def _mpls_meta_label_entry(stream: dict[str, Any], label: dict[str, int], index: int) -> dict[str, str]:
    label_field = workbench_mpls_label_field_name(index)
    tc_field = workbench_mpls_tc_field_name(index)
    ttl_field = workbench_mpls_ttl_field_name(index)
    return {
        "label": str(label["label"]),
        "label_mode": stream[f"{label_field}_mode"],
        "label_count": str(stream[f"{label_field}_count"]),
        "label_step": str(stream[f"{label_field}_step"]),
        "traffic_class": str(label["traffic_class"]),
        "traffic_class_mode": stream[f"{tc_field}_mode"],
        "traffic_class_count": str(stream[f"{tc_field}_count"]),
        "traffic_class_step": str(stream[f"{tc_field}_step"]),
        "bottom_of_stack": str(label["bottom_of_stack"]),
        "ttl": str(label["ttl"]),
        "ttl_mode": stream[f"{ttl_field}_mode"],
        "ttl_count": str(stream[f"{ttl_field}_count"]),
        "ttl_step": str(stream[f"{ttl_field}_step"]),
    }


def _vlan_meta_tag_entry(stream: dict[str, Any], index: int) -> dict[str, str | bool]:
    priority_field = workbench_vlan_priority_field_name(index)
    id_field = workbench_vlan_id_field_name(index)
    return {
        "is_override_tp_id": bool(stream[workbench_vlan_tpid_override_field_name(index)]),
        "tp_id": str(stream[workbench_vlan_tpid_field_name(index)]),
        "priority": str(stream[priority_field]),
        "priority_mode": stream[f"{priority_field}_mode"],
        "priority_count": str(stream[f"{priority_field}_count"]),
        "priority_step": str(stream[f"{priority_field}_step"]),
        "cfi": str(stream[workbench_vlan_cfi_field_name(index)]),
        "v_id": str(stream[id_field]),
        "v_id_mode": stream[f"{id_field}_mode"],
        "v_id_count": str(stream[f"{id_field}_count"]),
        "v_id_step": str(stream[f"{id_field}_step"]),
    }


def packet_meta(stream: dict[str, Any], packet_binary: str) -> str:
    ethernet_type = workbench_outer_ether_type(stream)
    ip_version = workbench_ip_version(stream)
    has_l3 = workbench_has_l3(stream)
    mpls_stack = workbench_mpls_stack(stream)
    first_mpls = mpls_stack[0] if mpls_stack else {
        "label": stream["mpls_label"],
        "traffic_class": stream["mpls_tc"],
        "bottom_of_stack": 1,
        "ttl": stream["mpls_ttl"],
    }
    meta = {
        "protocol_selection": {
            "is_tagged_vlan_selected": stream["vlan_enabled"],
            "is_mpls_selected": stream["mpls_enabled"],
            "is_vxlan_selected": stream["vxlan_enabled"],
            "is_gtpu_selected": stream["gtpu_enabled"],
            "is_pattern_selected": stream["payload_enabled"],
            "frame_length_type": stream["frame_length_type"],
            "is_arp_selected": workbench_has_arp(stream),
            "is_ipv4_selected": has_l3 and ip_version == 4,
            "is_ipv6_selected": has_l3 and ip_version == 6,
            "is_tcp_selected": stream["packet_type"].endswith("/TCP"),
            "is_udp_selected": stream["packet_type"].endswith("/UDP"),
            "is_gre_selected": stream["packet_type"].endswith("/GRE"),
            "is_sctp_selected": stream["packet_type"].endswith("/SCTP"),
            "is_icmp_selected": workbench_has_icmp(stream),
            "is_icmpv6_selected": stream["packet_type"].endswith("/ICMPv6"),
            "frame_length": str(stream["frame_length"]),
            "max_length": str(stream["frame_length_max"]),
            "min_length": str(stream["frame_length_min"]),
        },
        "ethernet": {
            "type": stream["ether_type"] if stream["ether_type_override"] else f"{ethernet_type:04x}",
            "is_override": bool(stream["ether_type_override"]),
            "override_source": "operator" if stream["ether_type_override"] else "auto",
            "src": stream["ether_src"],
            "dst": stream["ether_dst"],
        },
        "mac": {
            "source": {
                "address": stream["ether_src"],
                "count": str(stream["ether_src_count"]),
                "mode": stream["ether_src_mode"],
                "step": str(stream["ether_src_step"]),
            },
            "destination": {
                "address": stream["ether_dst"],
                "count": str(stream["ether_dst_count"]),
                "mode": stream["ether_dst_mode"],
                "step": str(stream["ether_dst_step"]),
            },
        },
        "arp": {
            "hardware_type": str(stream["arp_hardware_type"]),
            "protocol_type": stream["arp_protocol_type"],
            "hardware_size": str(stream["arp_hardware_size"]),
            "protocol_size": str(stream["arp_protocol_size"]),
            "operation": str(stream["arp_operation"]),
            "operation_mode": stream["arp_operation_mode"],
            "operation_count": str(stream["arp_operation_count"]),
            "operation_step": str(stream["arp_operation_step"]),
            "sender_mac": stream["arp_sender_mac"],
            "sender_mac_mode": stream["arp_sender_mac_mode"],
            "sender_mac_count": str(stream["arp_sender_mac_count"]),
            "sender_mac_step": str(stream["arp_sender_mac_step"]),
            "sender_ip": stream["arp_sender_ip"],
            "sender_ip_mode": stream["arp_sender_ip_mode"],
            "sender_ip_count": str(stream["arp_sender_ip_count"]),
            "sender_ip_step": str(stream["arp_sender_ip_step"]),
            "target_mac": stream["arp_target_mac"],
            "target_mac_mode": stream["arp_target_mac_mode"],
            "target_mac_count": str(stream["arp_target_mac_count"]),
            "target_mac_step": str(stream["arp_target_mac_step"]),
            "target_ip": stream["arp_target_ip"],
            "target_ip_mode": stream["arp_target_ip_mode"],
            "target_ip_count": str(stream["arp_target_ip_count"]),
            "target_ip_step": str(stream["arp_target_ip_step"]),
        },
        "vlan": {
            "is_override_tp_id": stream["vlan_tpid_override"],
            "tp_id": stream["vlan_tpid"],
            "priority": str(stream["vlan_priority"]),
            "priority_mode": stream["vlan_priority_mode"],
            "priority_count": str(stream["vlan_priority_count"]),
            "priority_step": str(stream["vlan_priority_step"]),
            "cfi": str(stream["vlan_cfi"]),
            "v_id": str(stream["vlan_id"]),
            "v_id_mode": stream["vlan_id_mode"],
            "v_id_count": str(stream["vlan_id_count"]),
            "v_id_step": str(stream["vlan_id_step"]),
            "tags": [_vlan_meta_tag_entry(stream, index) for index in range(1, workbench_vlan_tag_count(stream) + 1)],
        },
        "mpls": {
            "label": str(first_mpls["label"]),
            "label_mode": stream["mpls_label_mode"],
            "label_count": str(stream["mpls_label_count"]),
            "label_step": str(stream["mpls_label_step"]),
            "traffic_class": str(first_mpls["traffic_class"]),
            "traffic_class_mode": stream["mpls_tc_mode"],
            "traffic_class_count": str(stream["mpls_tc_count"]),
            "traffic_class_step": str(stream["mpls_tc_step"]),
            "bottom_of_stack": str(first_mpls["bottom_of_stack"]),
            "ttl": str(first_mpls["ttl"]),
            "ttl_mode": stream["mpls_ttl_mode"],
            "ttl_count": str(stream["mpls_ttl_count"]),
            "ttl_step": str(stream["mpls_ttl_step"]),
            "labels": [
                _mpls_meta_label_entry(stream, label, index + 1) for index, label in enumerate(mpls_stack)
            ],
        },
        "vxlan": {
            "vni": str(stream["vxlan_vni"]),
            "vni_mode": stream["vxlan_vni_mode"],
            "vni_count": str(stream["vxlan_vni_count"]),
            "vni_step": str(stream["vxlan_vni_step"]),
            "inner_ethernet": {
                "src": stream["vxlan_inner_ether_src"],
                "dst": stream["vxlan_inner_ether_dst"],
            },
            "inner_ip_version": stream["vxlan_inner_ip_version"],
            "inner_ipv4": {
                "src": stream["vxlan_inner_ipv4_src"],
                "src_mode": stream["vxlan_inner_ipv4_src_mode"],
                "src_count": str(stream["vxlan_inner_ipv4_src_count"]),
                "src_step": str(stream["vxlan_inner_ipv4_src_step"]),
                "dst": stream["vxlan_inner_ipv4_dst"],
                "dst_mode": stream["vxlan_inner_ipv4_dst_mode"],
                "dst_count": str(stream["vxlan_inner_ipv4_dst_count"]),
                "dst_step": str(stream["vxlan_inner_ipv4_dst_step"]),
                "ttl": str(stream["vxlan_inner_ipv4_ttl"]),
                "ttl_mode": stream["vxlan_inner_ipv4_ttl_mode"],
                "ttl_count": str(stream["vxlan_inner_ipv4_ttl_count"]),
                "ttl_step": str(stream["vxlan_inner_ipv4_ttl_step"]),
            },
            "inner_ipv6": {
                "src": stream["vxlan_inner_ipv6_src"],
                "src_mode": stream["vxlan_inner_ipv6_src_mode"],
                "src_count": str(stream["vxlan_inner_ipv6_src_count"]),
                "src_step": str(stream["vxlan_inner_ipv6_src_step"]),
                "dst": stream["vxlan_inner_ipv6_dst"],
                "dst_mode": stream["vxlan_inner_ipv6_dst_mode"],
                "dst_count": str(stream["vxlan_inner_ipv6_dst_count"]),
                "dst_step": str(stream["vxlan_inner_ipv6_dst_step"]),
                "hop_limit": str(stream["vxlan_inner_ipv6_hop_limit"]),
                "hop_limit_mode": stream["vxlan_inner_ipv6_hop_limit_mode"],
                "hop_limit_count": str(stream["vxlan_inner_ipv6_hop_limit_count"]),
                "hop_limit_step": str(stream["vxlan_inner_ipv6_hop_limit_step"]),
            },
            "inner_udp": {
                "src_port": stream["vxlan_inner_l4_src_port"],
                "src_port_mode": stream["vxlan_inner_l4_src_port_mode"],
                "src_port_count": str(stream["vxlan_inner_l4_src_port_count"]),
                "src_port_step": str(stream["vxlan_inner_l4_src_port_step"]),
                "dst_port": stream["vxlan_inner_l4_dst_port"],
                "dst_port_mode": stream["vxlan_inner_l4_dst_port_mode"],
                "dst_port_count": str(stream["vxlan_inner_l4_dst_port_count"]),
                "dst_port_step": str(stream["vxlan_inner_l4_dst_port_step"]),
            },
        },
        "gtpu": {
            "enabled": stream["gtpu_enabled"],
            "message_type": str(stream["gtpu_message_type"]),
            "teid": str(stream["gtpu_teid"]),
            "teid_mode": stream["gtpu_teid_mode"],
            "teid_count": str(stream["gtpu_teid_count"]),
            "teid_step": str(stream["gtpu_teid_step"]),
            "sequence_enabled": stream["gtpu_sequence_enabled"],
            "sequence": str(stream["gtpu_sequence"]),
            "sequence_mode": stream["gtpu_sequence_mode"],
            "sequence_count": str(stream["gtpu_sequence_count"]),
            "sequence_step": str(stream["gtpu_sequence_step"]),
            "n_pdu_enabled": stream["gtpu_npdu_enabled"],
            "n_pdu_number": str(stream["gtpu_npdu"]),
            "n_pdu_mode": stream["gtpu_npdu_mode"],
            "n_pdu_count": str(stream["gtpu_npdu_count"]),
            "n_pdu_step": str(stream["gtpu_npdu_step"]),
            "extension_enabled": stream["gtpu_extension_enabled"],
            "extension_type": "udp_port" if stream["gtpu_extension_enabled"] else "none",
            "extension_udp_port": str(stream["gtpu_extension_udp_port"]),
            "extension_udp_port_mode": stream["gtpu_extension_udp_port_mode"],
            "extension_udp_port_count": str(stream["gtpu_extension_udp_port_count"]),
            "extension_udp_port_step": str(stream["gtpu_extension_udp_port_step"]),
            "next_extension_header": f"{PROFILE_DEFAULT_GTPU_EXTENSION_TYPE_UDP_PORT:02x}"
            if stream["gtpu_extension_enabled"]
            else "00",
            "inner_ip_version": stream["gtpu_inner_ip_version"],
            "inner_ipv4": {
                "src": stream["gtpu_inner_ipv4_src"],
                "src_mode": stream["gtpu_inner_ipv4_src_mode"],
                "src_count": str(stream["gtpu_inner_ipv4_src_count"]),
                "src_step": str(stream["gtpu_inner_ipv4_src_step"]),
                "dst": stream["gtpu_inner_ipv4_dst"],
                "dst_mode": stream["gtpu_inner_ipv4_dst_mode"],
                "dst_count": str(stream["gtpu_inner_ipv4_dst_count"]),
                "dst_step": str(stream["gtpu_inner_ipv4_dst_step"]),
                "ttl": str(stream["gtpu_inner_ipv4_ttl"]),
                "ttl_mode": stream["gtpu_inner_ipv4_ttl_mode"],
                "ttl_count": str(stream["gtpu_inner_ipv4_ttl_count"]),
                "ttl_step": str(stream["gtpu_inner_ipv4_ttl_step"]),
            },
            "inner_ipv6": {
                "src": stream["gtpu_inner_ipv6_src"],
                "src_mode": stream["gtpu_inner_ipv6_src_mode"],
                "src_count": str(stream["gtpu_inner_ipv6_src_count"]),
                "src_step": str(stream["gtpu_inner_ipv6_src_step"]),
                "dst": stream["gtpu_inner_ipv6_dst"],
                "dst_mode": stream["gtpu_inner_ipv6_dst_mode"],
                "dst_count": str(stream["gtpu_inner_ipv6_dst_count"]),
                "dst_step": str(stream["gtpu_inner_ipv6_dst_step"]),
                "hop_limit": str(stream["gtpu_inner_ipv6_hop_limit"]),
                "hop_limit_mode": stream["gtpu_inner_ipv6_hop_limit_mode"],
                "hop_limit_count": str(stream["gtpu_inner_ipv6_hop_limit_count"]),
                "hop_limit_step": str(stream["gtpu_inner_ipv6_hop_limit_step"]),
            },
            "inner_udp": {
                "src_port": stream["gtpu_inner_l4_src_port"],
                "src_port_mode": stream["gtpu_inner_l4_src_port_mode"],
                "src_port_count": str(stream["gtpu_inner_l4_src_port_count"]),
                "src_port_step": str(stream["gtpu_inner_l4_src_port_step"]),
                "dst_port": stream["gtpu_inner_l4_dst_port"],
                "dst_port_mode": stream["gtpu_inner_l4_dst_port_mode"],
                "dst_port_count": str(stream["gtpu_inner_l4_dst_port_count"]),
                "dst_port_step": str(stream["gtpu_inner_l4_dst_port_step"]),
            },
        },
        "gre": {
            "checksum_present": stream["gre_checksum_present"],
            "is_override_checksum": stream["gre_checksum_override"],
            "checksum": stream["gre_checksum"],
            "key_present": stream["gre_key_present"],
            "key": str(stream["gre_key"]),
            "key_mode": stream["gre_key_mode"],
            "key_count": str(stream["gre_key_count"]),
            "key_step": str(stream["gre_key_step"]),
            "sequence_present": stream["gre_sequence_present"],
            "sequence": str(stream["gre_sequence"]),
            "sequence_mode": stream["gre_sequence_mode"],
            "sequence_count": str(stream["gre_sequence_count"]),
            "sequence_step": str(stream["gre_sequence_step"]),
            "protocol_type": stream["gre_protocol_type"],
            "inner_ip_version": stream["gre_inner_ip_version"],
            "inner_ipv4": {
                "src": stream["gre_inner_ipv4_src"],
                "src_mode": stream["gre_inner_ipv4_src_mode"],
                "src_count": str(stream["gre_inner_ipv4_src_count"]),
                "src_step": str(stream["gre_inner_ipv4_src_step"]),
                "dst": stream["gre_inner_ipv4_dst"],
                "dst_mode": stream["gre_inner_ipv4_dst_mode"],
                "dst_count": str(stream["gre_inner_ipv4_dst_count"]),
                "dst_step": str(stream["gre_inner_ipv4_dst_step"]),
                "ttl": str(stream["gre_inner_ipv4_ttl"]),
                "ttl_mode": stream["gre_inner_ipv4_ttl_mode"],
                "ttl_count": str(stream["gre_inner_ipv4_ttl_count"]),
                "ttl_step": str(stream["gre_inner_ipv4_ttl_step"]),
            },
            "inner_ipv6": {
                "src": stream["gre_inner_ipv6_src"],
                "src_mode": stream["gre_inner_ipv6_src_mode"],
                "src_count": str(stream["gre_inner_ipv6_src_count"]),
                "src_step": str(stream["gre_inner_ipv6_src_step"]),
                "dst": stream["gre_inner_ipv6_dst"],
                "dst_mode": stream["gre_inner_ipv6_dst_mode"],
                "dst_count": str(stream["gre_inner_ipv6_dst_count"]),
                "dst_step": str(stream["gre_inner_ipv6_dst_step"]),
                "hop_limit": str(stream["gre_inner_ipv6_hop_limit"]),
                "hop_limit_mode": stream["gre_inner_ipv6_hop_limit_mode"],
                "hop_limit_count": str(stream["gre_inner_ipv6_hop_limit_count"]),
                "hop_limit_step": str(stream["gre_inner_ipv6_hop_limit_step"]),
            },
            "inner_udp": {
                "src_port": stream["gre_inner_l4_src_port"],
                "src_port_mode": stream["gre_inner_l4_src_port_mode"],
                "src_port_count": str(stream["gre_inner_l4_src_port_count"]),
                "src_port_step": str(stream["gre_inner_l4_src_port_step"]),
                "dst_port": stream["gre_inner_l4_dst_port"],
                "dst_port_mode": stream["gre_inner_l4_dst_port_mode"],
                "dst_port_count": str(stream["gre_inner_l4_dst_port_count"]),
                "dst_port_step": str(stream["gre_inner_l4_dst_port_step"]),
            },
        },
        "ipv4": {
            "src": stream["ipv4_src"],
            "dst": stream["ipv4_dst"],
            "src_mode": stream["ipv4_src_mode"],
            "src_count": str(stream["ipv4_src_count"]),
            "src_step": str(stream["ipv4_src_step"]),
            "dst_mode": stream["ipv4_dst_mode"],
            "dst_count": str(stream["ipv4_dst_count"]),
            "dst_step": str(stream["ipv4_dst_step"]),
            "dscp": str(stream["ipv4_dscp"]),
            "dscp_mode": stream["ipv4_dscp_mode"],
            "dscp_count": str(stream["ipv4_dscp_count"]),
            "dscp_step": str(stream["ipv4_dscp_step"]),
            "ecn": str(stream["ipv4_ecn"]),
            "ecn_mode": stream["ipv4_ecn_mode"],
            "ecn_count": str(stream["ipv4_ecn_count"]),
            "ecn_step": str(stream["ipv4_ecn_step"]),
            "tos": str((stream["ipv4_dscp"] << 2) | stream["ipv4_ecn"]),
            "id": str(stream["ipv4_id"]),
            "id_mode": stream["ipv4_id_mode"],
            "id_count": str(stream["ipv4_id_count"]),
            "id_step": str(stream["ipv4_id_step"]),
            "flag_df": stream["ipv4_flag_df"],
            "flag_mf": stream["ipv4_flag_mf"],
            "fragment_offset": str(stream["ipv4_fragment_offset"]),
            "fragment_offset_mode": stream["ipv4_fragment_offset_mode"],
            "fragment_offset_count": str(stream["ipv4_fragment_offset_count"]),
            "fragment_offset_step": str(stream["ipv4_fragment_offset_step"]),
            "ttl": str(stream["ipv4_ttl"]),
            "ttl_mode": stream["ipv4_ttl_mode"],
            "ttl_count": str(stream["ipv4_ttl_count"]),
            "ttl_step": str(stream["ipv4_ttl_step"]),
            "is_override_checksum": stream["ipv4_checksum_override"],
            "checksum": stream["ipv4_checksum"],
        },
        "ipv6": {
            "src": stream["ipv6_src"],
            "dst": stream["ipv6_dst"],
            "src_mode": stream["ipv6_src_mode"],
            "src_count": str(stream["ipv6_src_count"]),
            "src_step": str(stream["ipv6_src_step"]),
            "dst_mode": stream["ipv6_dst_mode"],
            "dst_count": str(stream["ipv6_dst_count"]),
            "dst_step": str(stream["ipv6_dst_step"]),
            "traffic_class": str(stream["ipv6_traffic_class"]),
            "traffic_class_mode": stream["ipv6_traffic_class_mode"],
            "traffic_class_count": str(stream["ipv6_traffic_class_count"]),
            "traffic_class_step": str(stream["ipv6_traffic_class_step"]),
            "flow_label": str(stream["ipv6_flow_label"]),
            "flow_label_mode": stream["ipv6_flow_label_mode"],
            "flow_label_count": str(stream["ipv6_flow_label_count"]),
            "flow_label_step": str(stream["ipv6_flow_label_step"]),
            "hop_limit": str(stream["ipv6_hop_limit"]),
            "hop_limit_mode": stream["ipv6_hop_limit_mode"],
            "hop_limit_count": str(stream["ipv6_hop_limit_count"]),
            "hop_limit_step": str(stream["ipv6_hop_limit_step"]),
        },
        "l4": {
            "is_override_src_port": stream["l4_src_port_override"],
            "src_port": stream["l4_src_port"],
            "src_port_mode": stream["l4_src_port_mode"],
            "src_port_count": str(stream["l4_src_port_count"]),
            "src_port_step": str(stream["l4_src_port_step"]),
            "is_override_dst_port": stream["l4_dst_port_override"],
            "dst_port": stream["l4_dst_port"],
            "dst_port_mode": stream["l4_dst_port_mode"],
            "dst_port_count": str(stream["l4_dst_port_count"]),
            "dst_port_step": str(stream["l4_dst_port_step"]),
            "is_override_length": stream["udp_length_override"],
            "length": str(stream["udp_length"]),
            "length_mode": stream["udp_length_mode"],
            "length_count": str(stream["udp_length_count"]),
            "length_step": str(stream["udp_length_step"]),
            "sequence_number": str(stream["tcp_sequence_number"]),
            "sequence_mode": stream["tcp_sequence_mode"],
            "sequence_count": str(stream["tcp_sequence_count"]),
            "sequence_step": str(stream["tcp_sequence_step"]),
            "ack_number": str(stream["tcp_ack_number"]),
            "ack_mode": stream["tcp_ack_mode"],
            "ack_count": str(stream["tcp_ack_count"]),
            "ack_step": str(stream["tcp_ack_step"]),
            "window": str(stream["tcp_window"]),
            "window_mode": stream["tcp_window_mode"],
            "window_count": str(stream["tcp_window_count"]),
            "window_step": str(stream["tcp_window_step"]),
            "is_override_checksum": stream["udp_checksum_override"]
            if stream["packet_type"].endswith("/UDP")
            else stream["tcp_checksum_override"],
            "checksum": stream["udp_checksum"] if stream["packet_type"].endswith("/UDP") else stream["tcp_checksum"],
            "checksum_mode": stream["udp_checksum_mode"] if stream["packet_type"].endswith("/UDP") else stream["tcp_checksum_mode"],
            "checksum_count": str(stream["udp_checksum_count"])
            if stream["packet_type"].endswith("/UDP")
            else str(stream["tcp_checksum_count"]),
            "checksum_step": str(stream["udp_checksum_step"])
            if stream["packet_type"].endswith("/UDP")
            else str(stream["tcp_checksum_step"]),
            "mss_enabled": stream["tcp_option_mss_enabled"],
            "mss": str(stream["tcp_option_mss"]),
            "mss_mode": stream["tcp_option_mss_mode"],
            "mss_count": str(stream["tcp_option_mss_count"]),
            "mss_step": str(stream["tcp_option_mss_step"]),
            "window_scale_enabled": stream["tcp_option_window_scale_enabled"],
            "window_scale": str(stream["tcp_option_window_scale"]),
            "window_scale_mode": stream["tcp_option_window_scale_mode"],
            "window_scale_count": str(stream["tcp_option_window_scale_count"]),
            "window_scale_step": str(stream["tcp_option_window_scale_step"]),
            "sack_permitted_enabled": stream["tcp_option_sack_permitted_enabled"],
            "sack_blocks_enabled": stream["tcp_option_sack_blocks_enabled"],
            "sack_left_edge": str(stream["tcp_option_sack_left_edge"]),
            "sack_left_edge_mode": stream["tcp_option_sack_left_edge_mode"],
            "sack_left_edge_count": str(stream["tcp_option_sack_left_edge_count"]),
            "sack_left_edge_step": str(stream["tcp_option_sack_left_edge_step"]),
            "sack_right_edge": str(stream["tcp_option_sack_right_edge"]),
            "sack_right_edge_mode": stream["tcp_option_sack_right_edge_mode"],
            "sack_right_edge_count": str(stream["tcp_option_sack_right_edge_count"]),
            "sack_right_edge_step": str(stream["tcp_option_sack_right_edge_step"]),
            "timestamp_enabled": stream["tcp_option_timestamp_enabled"],
            "timestamp_value": str(stream["tcp_option_timestamp_value"]),
            "timestamp_value_mode": stream["tcp_option_timestamp_value_mode"],
            "timestamp_value_count": str(stream["tcp_option_timestamp_value_count"]),
            "timestamp_value_step": str(stream["tcp_option_timestamp_value_step"]),
            "timestamp_echo": str(stream["tcp_option_timestamp_echo"]),
            "timestamp_echo_mode": stream["tcp_option_timestamp_echo_mode"],
            "timestamp_echo_count": str(stream["tcp_option_timestamp_echo_count"]),
            "timestamp_echo_step": str(stream["tcp_option_timestamp_echo_step"]),
            "icmp_type": str(stream["icmp_type"]),
            "icmp_type_mode": stream["icmp_type_mode"],
            "icmp_type_count": str(stream["icmp_type_count"]),
            "icmp_type_step": str(stream["icmp_type_step"]),
            "icmp_code": str(stream["icmp_code"]),
            "icmp_code_mode": stream["icmp_code_mode"],
            "icmp_code_count": str(stream["icmp_code_count"]),
            "icmp_code_step": str(stream["icmp_code_step"]),
            "icmp_identifier": str(stream["icmp_identifier"]),
            "icmp_identifier_mode": stream["icmp_identifier_mode"],
            "icmp_identifier_count": str(stream["icmp_identifier_count"]),
            "icmp_identifier_step": str(stream["icmp_identifier_step"]),
            "icmp_sequence": str(stream["icmp_sequence"]),
            "icmp_sequence_mode": stream["icmp_sequence_mode"],
            "icmp_sequence_count": str(stream["icmp_sequence_count"]),
            "icmp_sequence_step": str(stream["icmp_sequence_step"]),
            "icmp_is_override_checksum": stream["icmp_checksum_override"],
            "icmp_checksum": stream["icmp_checksum"],
            "icmpv6_nd_target": stream["icmpv6_nd_target"],
            "icmpv6_nd_include_option": stream["icmpv6_nd_include_option"],
            "icmpv6_nd_option_mac": stream["icmpv6_nd_option_mac"],
            "icmpv6_nd_na_router": stream["icmpv6_nd_na_router"],
            "icmpv6_nd_na_solicited": stream["icmpv6_nd_na_solicited"],
            "icmpv6_nd_na_override": stream["icmpv6_nd_na_override"],
            "icmpv6_rs_include_slla": stream["icmpv6_rs_include_slla"],
            "icmpv6_rs_slla_mac": stream["icmpv6_rs_slla_mac"],
            "icmpv6_ra_cur_hop_limit": str(stream["icmpv6_ra_cur_hop_limit"]),
            "icmpv6_ra_managed": stream["icmpv6_ra_managed"],
            "icmpv6_ra_other": stream["icmpv6_ra_other"],
            "icmpv6_ra_router_lifetime": str(stream["icmpv6_ra_router_lifetime"]),
            "icmpv6_ra_reachable_time": str(stream["icmpv6_ra_reachable_time"]),
            "icmpv6_ra_retrans_timer": str(stream["icmpv6_ra_retrans_timer"]),
            "icmpv6_ra_include_slla": stream["icmpv6_ra_include_slla"],
            "icmpv6_ra_slla_mac": stream["icmpv6_ra_slla_mac"],
            "icmpv6_ra_include_prefix": stream["icmpv6_ra_include_prefix"],
            "icmpv6_ra_prefix": stream["icmpv6_ra_prefix"],
            "icmpv6_ra_prefix_length": str(stream["icmpv6_ra_prefix_length"]),
            "icmpv6_ra_prefix_on_link": stream["icmpv6_ra_prefix_on_link"],
            "icmpv6_ra_prefix_autonomous": stream["icmpv6_ra_prefix_autonomous"],
            "icmpv6_ra_prefix_valid_lifetime": str(stream["icmpv6_ra_prefix_valid_lifetime"]),
            "icmpv6_ra_prefix_preferred_lifetime": str(stream["icmpv6_ra_prefix_preferred_lifetime"]),
            "urgent_pointer": str(stream["tcp_urgent_pointer"]),
            "urgent_pointer_mode": stream["tcp_urgent_pointer_mode"],
            "urgent_pointer_count": str(stream["tcp_urgent_pointer_count"]),
            "urgent_pointer_step": str(stream["tcp_urgent_pointer_step"]),
            "flags_mode": stream["tcp_flags_mode"],
            "flags_count": str(stream["tcp_flags_count"]),
            "flags_step": str(stream["tcp_flags_step"]),
            "is_urg": stream["tcp_flag_urg"],
            "is_ack": stream["tcp_flag_ack"],
            "is_psh": stream["tcp_flag_psh"],
            "is_rst": stream["tcp_flag_rst"],
            "is_sync": stream["tcp_flag_syn"],
            "is_fin": stream["tcp_flag_fin"],
        },
        "sctp": {
            "verification_tag": str(stream["sctp_verification_tag"]),
            "verification_tag_mode": stream["sctp_verification_tag_mode"],
            "verification_tag_count": str(stream["sctp_verification_tag_count"]),
            "verification_tag_step": str(stream["sctp_verification_tag_step"]),
            "is_override_checksum": stream["sctp_checksum_override"],
            "checksum": stream["sctp_checksum"],
            "data_flags": str(stream["sctp_data_flags"]),
            "data_flags_mode": stream["sctp_data_flags_mode"],
            "data_flags_count": str(stream["sctp_data_flags_count"]),
            "data_flags_step": str(stream["sctp_data_flags_step"]),
            "tsn": str(stream["sctp_tsn"]),
            "tsn_mode": stream["sctp_tsn_mode"],
            "tsn_count": str(stream["sctp_tsn_count"]),
            "tsn_step": str(stream["sctp_tsn_step"]),
            "stream_id": str(stream["sctp_stream_id"]),
            "stream_id_mode": stream["sctp_stream_id_mode"],
            "stream_id_count": str(stream["sctp_stream_id_count"]),
            "stream_id_step": str(stream["sctp_stream_id_step"]),
            "stream_sequence": str(stream["sctp_stream_sequence"]),
            "stream_sequence_mode": stream["sctp_stream_sequence_mode"],
            "stream_sequence_count": str(stream["sctp_stream_sequence_count"]),
            "stream_sequence_step": str(stream["sctp_stream_sequence_step"]),
            "payload_protocol_id": str(stream["sctp_payload_protocol_id"]),
            "payload_protocol_id_mode": stream["sctp_payload_protocol_id_mode"],
            "payload_protocol_id_count": str(stream["sctp_payload_protocol_id_count"]),
            "payload_protocol_id_step": str(stream["sctp_payload_protocol_id_step"]),
        },
        "dns": {
            "enabled": stream["dns_enabled"],
            "transaction_id": str(stream["dns_transaction_id"]),
            "transaction_id_mode": stream["dns_transaction_id_mode"],
            "transaction_id_count": str(stream["dns_transaction_id_count"]),
            "transaction_id_step": str(stream["dns_transaction_id_step"]),
            "flags": stream["dns_flags"],
            "flags_mode": stream["dns_flags_mode"],
            "flags_count": str(stream["dns_flags_count"]),
            "flags_step": str(stream["dns_flags_step"]),
            "query_name": stream["dns_query_name"],
            "query_type": str(stream["dns_query_type"]),
            "query_type_mode": stream["dns_query_type_mode"],
            "query_type_count": str(stream["dns_query_type_count"]),
            "query_type_step": str(stream["dns_query_type_step"]),
            "query_class": str(stream["dns_query_class"]),
            "query_class_mode": stream["dns_query_class_mode"],
            "query_class_count": str(stream["dns_query_class_count"]),
            "query_class_step": str(stream["dns_query_class_step"]),
            "answer_enabled": stream["dns_answer_enabled"],
            "answer_ttl": str(stream["dns_answer_ttl"]),
            "answer_ttl_mode": stream["dns_answer_ttl_mode"],
            "answer_ttl_count": str(stream["dns_answer_ttl_count"]),
            "answer_ttl_step": str(stream["dns_answer_ttl_step"]),
            "answer_ipv4": stream["dns_answer_ipv4"],
            "answer_ipv4_mode": stream["dns_answer_ipv4_mode"],
            "answer_ipv4_count": str(stream["dns_answer_ipv4_count"]),
            "answer_ipv4_step": str(stream["dns_answer_ipv4_step"]),
        },
        "dhcp": {
            "enabled": stream["dhcp_enabled"],
            "operation": str(stream["dhcp_operation"]),
            "operation_mode": stream["dhcp_operation_mode"],
            "operation_count": str(stream["dhcp_operation_count"]),
            "operation_step": str(stream["dhcp_operation_step"]),
            "hops": str(stream["dhcp_hops"]),
            "hops_mode": stream["dhcp_hops_mode"],
            "hops_count": str(stream["dhcp_hops_count"]),
            "hops_step": str(stream["dhcp_hops_step"]),
            "seconds": str(stream["dhcp_seconds"]),
            "seconds_mode": stream["dhcp_seconds_mode"],
            "seconds_count": str(stream["dhcp_seconds_count"]),
            "seconds_step": str(stream["dhcp_seconds_step"]),
            "message_type": str(stream["dhcp_message_type"]),
            "message_type_mode": stream["dhcp_message_type_mode"],
            "message_type_count": str(stream["dhcp_message_type_count"]),
            "message_type_step": str(stream["dhcp_message_type_step"]),
            "xid": str(stream["dhcp_xid"]),
            "xid_mode": stream["dhcp_xid_mode"],
            "xid_count": str(stream["dhcp_xid_count"]),
            "xid_step": str(stream["dhcp_xid_step"]),
            "flags": stream["dhcp_flags"],
            "flags_mode": stream["dhcp_flags_mode"],
            "flags_count": str(stream["dhcp_flags_count"]),
            "flags_step": str(stream["dhcp_flags_step"]),
            "client_ip": stream["dhcp_client_ip"],
            "client_ip_mode": stream["dhcp_client_ip_mode"],
            "client_ip_count": str(stream["dhcp_client_ip_count"]),
            "client_ip_step": str(stream["dhcp_client_ip_step"]),
            "your_ip": stream["dhcp_your_ip"],
            "your_ip_mode": stream["dhcp_your_ip_mode"],
            "your_ip_count": str(stream["dhcp_your_ip_count"]),
            "your_ip_step": str(stream["dhcp_your_ip_step"]),
            "server_ip": stream["dhcp_server_ip"],
            "server_ip_mode": stream["dhcp_server_ip_mode"],
            "server_ip_count": str(stream["dhcp_server_ip_count"]),
            "server_ip_step": str(stream["dhcp_server_ip_step"]),
            "relay_ip": stream["dhcp_relay_ip"],
            "relay_ip_mode": stream["dhcp_relay_ip_mode"],
            "relay_ip_count": str(stream["dhcp_relay_ip_count"]),
            "relay_ip_step": str(stream["dhcp_relay_ip_step"]),
            "client_mac": stream["dhcp_client_mac"],
            "client_mac_mode": stream["dhcp_client_mac_mode"],
            "client_mac_count": str(stream["dhcp_client_mac_count"]),
            "client_mac_step": str(stream["dhcp_client_mac_step"]),
            "hostname": stream["dhcp_hostname"],
            "requested_ip": stream["dhcp_requested_ip"],
            "requested_ip_mode": stream["dhcp_requested_ip_mode"],
            "requested_ip_count": str(stream["dhcp_requested_ip_count"]),
            "requested_ip_step": str(stream["dhcp_requested_ip_step"]),
            "server_id": stream["dhcp_server_id"],
            "server_id_mode": stream["dhcp_server_id_mode"],
            "server_id_count": str(stream["dhcp_server_id_count"]),
            "server_id_step": str(stream["dhcp_server_id_step"]),
            "parameter_request_list": stream["dhcp_parameter_request_list"],
            "lease_time": str(stream["dhcp_lease_time"]),
            "lease_time_mode": stream["dhcp_lease_time_mode"],
            "lease_time_count": str(stream["dhcp_lease_time_count"]),
            "lease_time_step": str(stream["dhcp_lease_time_step"]),
            "renewal_time": str(stream["dhcp_renewal_time"]),
            "renewal_time_mode": stream["dhcp_renewal_time_mode"],
            "renewal_time_count": str(stream["dhcp_renewal_time_count"]),
            "renewal_time_step": str(stream["dhcp_renewal_time_step"]),
            "rebinding_time": str(stream["dhcp_rebinding_time"]),
            "rebinding_time_mode": stream["dhcp_rebinding_time_mode"],
            "rebinding_time_count": str(stream["dhcp_rebinding_time_count"]),
            "rebinding_time_step": str(stream["dhcp_rebinding_time_step"]),
        },
        "payload": {
            "type": stream["payload_type"],
            "pattern": stream["payload_pattern"],
        },
        "packet": {"binary": packet_binary},
        "model_version": "1.0",
    }
    return base64.b64encode(yaml.safe_dump(meta, sort_keys=True).encode("utf-8")).decode("ascii")
