import type { ProfileWorkbenchStream } from "../../../api";
import {
  runGreChecksumChange,
  runGreChecksumOverrideChange,
  runGreChecksumSelectionChange,
  runGreInnerIpv4DestinationChange,
  runGreInnerIpv4DestinationCountChange,
  runGreInnerIpv4DestinationModeChange,
  runGreInnerIpv4DestinationStepChange,
  runGreInnerIpv4SourceChange,
  runGreInnerIpv4SourceCountChange,
  runGreInnerIpv4SourceModeChange,
  runGreInnerIpv4SourceStepChange,
  runGreInnerIpv4TtlChange,
  runGreInnerIpv4TtlCountChange,
  runGreInnerIpv4TtlModeChange,
  runGreInnerIpv4TtlStepChange,
  runGreInnerIpv6DestinationChange,
  runGreInnerIpv6DestinationCountChange,
  runGreInnerIpv6DestinationModeChange,
  runGreInnerIpv6DestinationStepChange,
  runGreInnerIpv6HopLimitChange,
  runGreInnerIpv6HopLimitCountChange,
  runGreInnerIpv6HopLimitModeChange,
  runGreInnerIpv6HopLimitStepChange,
  runGreInnerIpv6SourceChange,
  runGreInnerIpv6SourceCountChange,
  runGreInnerIpv6SourceModeChange,
  runGreInnerIpv6SourceStepChange,
  runGreInnerL4DestinationPortChange,
  runGreInnerL4DestinationPortCountChange,
  runGreInnerL4DestinationPortModeChange,
  runGreInnerL4DestinationPortStepChange,
  runGreInnerL4SourcePortChange,
  runGreInnerL4SourcePortCountChange,
  runGreInnerL4SourcePortModeChange,
  runGreInnerL4SourcePortStepChange,
  runGreKeyChange,
  runGreKeyCountChange,
  runGreKeyModeChange,
  runGreKeySelectionChange,
  runGreKeyStepChange,
  runGreSequenceChange,
  runGreSequenceCountChange,
  runGreSequenceModeChange,
  runGreSequenceSelectionChange,
  runGreSequenceStepChange,
  runGtpuExtensionSelectionChange,
  runGtpuExtensionUdpPortChange,
  runGtpuExtensionUdpPortCountChange,
  runGtpuExtensionUdpPortModeChange,
  runGtpuExtensionUdpPortStepChange,
  runGtpuInnerIpv4DestinationChange,
  runGtpuInnerIpv4DestinationCountChange,
  runGtpuInnerIpv4DestinationModeChange,
  runGtpuInnerIpv4DestinationStepChange,
  runGtpuInnerIpv4SourceChange,
  runGtpuInnerIpv4SourceCountChange,
  runGtpuInnerIpv4SourceModeChange,
  runGtpuInnerIpv4SourceStepChange,
  runGtpuInnerIpv4TtlChange,
  runGtpuInnerIpv4TtlCountChange,
  runGtpuInnerIpv4TtlModeChange,
  runGtpuInnerIpv4TtlStepChange,
  runGtpuInnerIpv6DestinationChange,
  runGtpuInnerIpv6DestinationCountChange,
  runGtpuInnerIpv6DestinationModeChange,
  runGtpuInnerIpv6DestinationStepChange,
  runGtpuInnerIpv6HopLimitChange,
  runGtpuInnerIpv6HopLimitCountChange,
  runGtpuInnerIpv6HopLimitModeChange,
  runGtpuInnerIpv6HopLimitStepChange,
  runGtpuInnerIpv6SourceChange,
  runGtpuInnerIpv6SourceCountChange,
  runGtpuInnerIpv6SourceModeChange,
  runGtpuInnerIpv6SourceStepChange,
  runGtpuInnerL4DestinationPortChange,
  runGtpuInnerL4DestinationPortCountChange,
  runGtpuInnerL4DestinationPortModeChange,
  runGtpuInnerL4DestinationPortStepChange,
  runGtpuInnerL4SourcePortChange,
  runGtpuInnerL4SourcePortCountChange,
  runGtpuInnerL4SourcePortModeChange,
  runGtpuInnerL4SourcePortStepChange,
  runGtpuMessageTypeChange,
  runGtpuNpduChange,
  runGtpuNpduCountChange,
  runGtpuNpduModeChange,
  runGtpuNpduSelectionChange,
  runGtpuNpduStepChange,
  runGtpuSequenceChange,
  runGtpuSequenceCountChange,
  runGtpuSequenceModeChange,
  runGtpuSequenceSelectionChange,
  runGtpuSequenceStepChange,
  runGtpuTeidChange,
  runGtpuTeidCountChange,
  runGtpuTeidModeChange,
  runGtpuTeidStepChange,
  runVxlanInnerEtherDestinationChange,
  runVxlanInnerEtherSourceChange,
  runVxlanInnerIpv4DestinationChange,
  runVxlanInnerIpv4DestinationCountChange,
  runVxlanInnerIpv4DestinationModeChange,
  runVxlanInnerIpv4DestinationStepChange,
  runVxlanInnerIpv4SourceChange,
  runVxlanInnerIpv4SourceCountChange,
  runVxlanInnerIpv4SourceModeChange,
  runVxlanInnerIpv4SourceStepChange,
  runVxlanInnerIpv4TtlChange,
  runVxlanInnerIpv4TtlCountChange,
  runVxlanInnerIpv4TtlModeChange,
  runVxlanInnerIpv4TtlStepChange,
  runVxlanInnerIpv6DestinationChange,
  runVxlanInnerIpv6DestinationCountChange,
  runVxlanInnerIpv6DestinationModeChange,
  runVxlanInnerIpv6DestinationStepChange,
  runVxlanInnerIpv6HopLimitChange,
  runVxlanInnerIpv6HopLimitCountChange,
  runVxlanInnerIpv6HopLimitModeChange,
  runVxlanInnerIpv6HopLimitStepChange,
  runVxlanInnerIpv6SourceChange,
  runVxlanInnerIpv6SourceCountChange,
  runVxlanInnerIpv6SourceModeChange,
  runVxlanInnerIpv6SourceStepChange,
  runVxlanInnerL4DestinationPortChange,
  runVxlanInnerL4DestinationPortCountChange,
  runVxlanInnerL4DestinationPortModeChange,
  runVxlanInnerL4DestinationPortStepChange,
  runVxlanInnerL4SourcePortChange,
  runVxlanInnerL4SourcePortCountChange,
  runVxlanInnerL4SourcePortModeChange,
  runVxlanInnerL4SourcePortStepChange,
  runVxlanVniChange,
  runVxlanVniCountChange,
  runVxlanVniModeChange,
  runVxlanVniStepChange,
  type StreamPatchHandlers
} from "./streamPatchModel";

type TunnelPatchRunner<Value> = (
  value: Value,
  stream: ProfileWorkbenchStream | null,
  handlers: StreamPatchHandlers
) => boolean;

export type WorkspaceProtocolDataTunnelHandlerOptions = {
  selectedStream: ProfileWorkbenchStream | null;
  streamPatchHandlers: StreamPatchHandlers;
};

export function workspaceProtocolDataTunnelHandlers({
  selectedStream,
  streamPatchHandlers
}: WorkspaceProtocolDataTunnelHandlerOptions) {
  const bind =
    <Value,>(runner: TunnelPatchRunner<Value>) =>
    (value: Value) =>
      runner(value, selectedStream, streamPatchHandlers);

  return {
    changeGreChecksum: bind(runGreChecksumChange),
    changeGreChecksumOverride: bind(runGreChecksumOverrideChange),
    changeGreChecksumSelection: bind(runGreChecksumSelectionChange),
    changeGreInnerIpv4Destination: bind(runGreInnerIpv4DestinationChange),
    changeGreInnerIpv4DestinationCount: bind(runGreInnerIpv4DestinationCountChange),
    changeGreInnerIpv4DestinationMode: bind(runGreInnerIpv4DestinationModeChange),
    changeGreInnerIpv4DestinationStep: bind(runGreInnerIpv4DestinationStepChange),
    changeGreInnerIpv4Source: bind(runGreInnerIpv4SourceChange),
    changeGreInnerIpv4SourceCount: bind(runGreInnerIpv4SourceCountChange),
    changeGreInnerIpv4SourceMode: bind(runGreInnerIpv4SourceModeChange),
    changeGreInnerIpv4SourceStep: bind(runGreInnerIpv4SourceStepChange),
    changeGreInnerIpv4Ttl: bind(runGreInnerIpv4TtlChange),
    changeGreInnerIpv4TtlCount: bind(runGreInnerIpv4TtlCountChange),
    changeGreInnerIpv4TtlMode: bind(runGreInnerIpv4TtlModeChange),
    changeGreInnerIpv4TtlStep: bind(runGreInnerIpv4TtlStepChange),
    changeGreInnerIpv6Destination: bind(runGreInnerIpv6DestinationChange),
    changeGreInnerIpv6DestinationCount: bind(runGreInnerIpv6DestinationCountChange),
    changeGreInnerIpv6DestinationMode: bind(runGreInnerIpv6DestinationModeChange),
    changeGreInnerIpv6DestinationStep: bind(runGreInnerIpv6DestinationStepChange),
    changeGreInnerIpv6HopLimit: bind(runGreInnerIpv6HopLimitChange),
    changeGreInnerIpv6HopLimitCount: bind(runGreInnerIpv6HopLimitCountChange),
    changeGreInnerIpv6HopLimitMode: bind(runGreInnerIpv6HopLimitModeChange),
    changeGreInnerIpv6HopLimitStep: bind(runGreInnerIpv6HopLimitStepChange),
    changeGreInnerIpv6Source: bind(runGreInnerIpv6SourceChange),
    changeGreInnerIpv6SourceCount: bind(runGreInnerIpv6SourceCountChange),
    changeGreInnerIpv6SourceMode: bind(runGreInnerIpv6SourceModeChange),
    changeGreInnerIpv6SourceStep: bind(runGreInnerIpv6SourceStepChange),
    changeGreInnerL4DestinationPort: bind(runGreInnerL4DestinationPortChange),
    changeGreInnerL4DestinationPortCount: bind(runGreInnerL4DestinationPortCountChange),
    changeGreInnerL4DestinationPortMode: bind(runGreInnerL4DestinationPortModeChange),
    changeGreInnerL4DestinationPortStep: bind(runGreInnerL4DestinationPortStepChange),
    changeGreInnerL4SourcePort: bind(runGreInnerL4SourcePortChange),
    changeGreInnerL4SourcePortCount: bind(runGreInnerL4SourcePortCountChange),
    changeGreInnerL4SourcePortMode: bind(runGreInnerL4SourcePortModeChange),
    changeGreInnerL4SourcePortStep: bind(runGreInnerL4SourcePortStepChange),
    changeGreKey: bind(runGreKeyChange),
    changeGreKeyCount: bind(runGreKeyCountChange),
    changeGreKeyMode: bind(runGreKeyModeChange),
    changeGreKeySelection: bind(runGreKeySelectionChange),
    changeGreKeyStep: bind(runGreKeyStepChange),
    changeGreSequence: bind(runGreSequenceChange),
    changeGreSequenceCount: bind(runGreSequenceCountChange),
    changeGreSequenceMode: bind(runGreSequenceModeChange),
    changeGreSequenceSelection: bind(runGreSequenceSelectionChange),
    changeGreSequenceStep: bind(runGreSequenceStepChange),
    changeGtpuExtensionSelection: bind(runGtpuExtensionSelectionChange),
    changeGtpuExtensionUdpPort: bind(runGtpuExtensionUdpPortChange),
    changeGtpuExtensionUdpPortCount: bind(runGtpuExtensionUdpPortCountChange),
    changeGtpuExtensionUdpPortMode: bind(runGtpuExtensionUdpPortModeChange),
    changeGtpuExtensionUdpPortStep: bind(runGtpuExtensionUdpPortStepChange),
    changeGtpuInnerIpv4Destination: bind(runGtpuInnerIpv4DestinationChange),
    changeGtpuInnerIpv4DestinationCount: bind(runGtpuInnerIpv4DestinationCountChange),
    changeGtpuInnerIpv4DestinationMode: bind(runGtpuInnerIpv4DestinationModeChange),
    changeGtpuInnerIpv4DestinationStep: bind(runGtpuInnerIpv4DestinationStepChange),
    changeGtpuInnerIpv4Source: bind(runGtpuInnerIpv4SourceChange),
    changeGtpuInnerIpv4SourceCount: bind(runGtpuInnerIpv4SourceCountChange),
    changeGtpuInnerIpv4SourceMode: bind(runGtpuInnerIpv4SourceModeChange),
    changeGtpuInnerIpv4SourceStep: bind(runGtpuInnerIpv4SourceStepChange),
    changeGtpuInnerIpv4Ttl: bind(runGtpuInnerIpv4TtlChange),
    changeGtpuInnerIpv4TtlCount: bind(runGtpuInnerIpv4TtlCountChange),
    changeGtpuInnerIpv4TtlMode: bind(runGtpuInnerIpv4TtlModeChange),
    changeGtpuInnerIpv4TtlStep: bind(runGtpuInnerIpv4TtlStepChange),
    changeGtpuInnerIpv6Destination: bind(runGtpuInnerIpv6DestinationChange),
    changeGtpuInnerIpv6DestinationCount: bind(runGtpuInnerIpv6DestinationCountChange),
    changeGtpuInnerIpv6DestinationMode: bind(runGtpuInnerIpv6DestinationModeChange),
    changeGtpuInnerIpv6DestinationStep: bind(runGtpuInnerIpv6DestinationStepChange),
    changeGtpuInnerIpv6HopLimit: bind(runGtpuInnerIpv6HopLimitChange),
    changeGtpuInnerIpv6HopLimitCount: bind(runGtpuInnerIpv6HopLimitCountChange),
    changeGtpuInnerIpv6HopLimitMode: bind(runGtpuInnerIpv6HopLimitModeChange),
    changeGtpuInnerIpv6HopLimitStep: bind(runGtpuInnerIpv6HopLimitStepChange),
    changeGtpuInnerIpv6Source: bind(runGtpuInnerIpv6SourceChange),
    changeGtpuInnerIpv6SourceCount: bind(runGtpuInnerIpv6SourceCountChange),
    changeGtpuInnerIpv6SourceMode: bind(runGtpuInnerIpv6SourceModeChange),
    changeGtpuInnerIpv6SourceStep: bind(runGtpuInnerIpv6SourceStepChange),
    changeGtpuInnerL4DestinationPort: bind(runGtpuInnerL4DestinationPortChange),
    changeGtpuInnerL4DestinationPortCount: bind(runGtpuInnerL4DestinationPortCountChange),
    changeGtpuInnerL4DestinationPortMode: bind(runGtpuInnerL4DestinationPortModeChange),
    changeGtpuInnerL4DestinationPortStep: bind(runGtpuInnerL4DestinationPortStepChange),
    changeGtpuInnerL4SourcePort: bind(runGtpuInnerL4SourcePortChange),
    changeGtpuInnerL4SourcePortCount: bind(runGtpuInnerL4SourcePortCountChange),
    changeGtpuInnerL4SourcePortMode: bind(runGtpuInnerL4SourcePortModeChange),
    changeGtpuInnerL4SourcePortStep: bind(runGtpuInnerL4SourcePortStepChange),
    changeGtpuMessageType: bind(runGtpuMessageTypeChange),
    changeGtpuNpdu: bind(runGtpuNpduChange),
    changeGtpuNpduCount: bind(runGtpuNpduCountChange),
    changeGtpuNpduMode: bind(runGtpuNpduModeChange),
    changeGtpuNpduSelection: bind(runGtpuNpduSelectionChange),
    changeGtpuNpduStep: bind(runGtpuNpduStepChange),
    changeGtpuSequence: bind(runGtpuSequenceChange),
    changeGtpuSequenceCount: bind(runGtpuSequenceCountChange),
    changeGtpuSequenceMode: bind(runGtpuSequenceModeChange),
    changeGtpuSequenceSelection: bind(runGtpuSequenceSelectionChange),
    changeGtpuSequenceStep: bind(runGtpuSequenceStepChange),
    changeGtpuTeid: bind(runGtpuTeidChange),
    changeGtpuTeidCount: bind(runGtpuTeidCountChange),
    changeGtpuTeidMode: bind(runGtpuTeidModeChange),
    changeGtpuTeidStep: bind(runGtpuTeidStepChange),
    changeVxlanInnerEtherDestination: bind(runVxlanInnerEtherDestinationChange),
    changeVxlanInnerEtherSource: bind(runVxlanInnerEtherSourceChange),
    changeVxlanInnerIpv4Destination: bind(runVxlanInnerIpv4DestinationChange),
    changeVxlanInnerIpv4DestinationCount: bind(runVxlanInnerIpv4DestinationCountChange),
    changeVxlanInnerIpv4DestinationMode: bind(runVxlanInnerIpv4DestinationModeChange),
    changeVxlanInnerIpv4DestinationStep: bind(runVxlanInnerIpv4DestinationStepChange),
    changeVxlanInnerIpv4Source: bind(runVxlanInnerIpv4SourceChange),
    changeVxlanInnerIpv4SourceCount: bind(runVxlanInnerIpv4SourceCountChange),
    changeVxlanInnerIpv4SourceMode: bind(runVxlanInnerIpv4SourceModeChange),
    changeVxlanInnerIpv4SourceStep: bind(runVxlanInnerIpv4SourceStepChange),
    changeVxlanInnerIpv4Ttl: bind(runVxlanInnerIpv4TtlChange),
    changeVxlanInnerIpv4TtlCount: bind(runVxlanInnerIpv4TtlCountChange),
    changeVxlanInnerIpv4TtlMode: bind(runVxlanInnerIpv4TtlModeChange),
    changeVxlanInnerIpv4TtlStep: bind(runVxlanInnerIpv4TtlStepChange),
    changeVxlanInnerIpv6Destination: bind(runVxlanInnerIpv6DestinationChange),
    changeVxlanInnerIpv6DestinationCount: bind(runVxlanInnerIpv6DestinationCountChange),
    changeVxlanInnerIpv6DestinationMode: bind(runVxlanInnerIpv6DestinationModeChange),
    changeVxlanInnerIpv6DestinationStep: bind(runVxlanInnerIpv6DestinationStepChange),
    changeVxlanInnerIpv6HopLimit: bind(runVxlanInnerIpv6HopLimitChange),
    changeVxlanInnerIpv6HopLimitCount: bind(runVxlanInnerIpv6HopLimitCountChange),
    changeVxlanInnerIpv6HopLimitMode: bind(runVxlanInnerIpv6HopLimitModeChange),
    changeVxlanInnerIpv6HopLimitStep: bind(runVxlanInnerIpv6HopLimitStepChange),
    changeVxlanInnerIpv6Source: bind(runVxlanInnerIpv6SourceChange),
    changeVxlanInnerIpv6SourceCount: bind(runVxlanInnerIpv6SourceCountChange),
    changeVxlanInnerIpv6SourceMode: bind(runVxlanInnerIpv6SourceModeChange),
    changeVxlanInnerIpv6SourceStep: bind(runVxlanInnerIpv6SourceStepChange),
    changeVxlanInnerL4DestinationPort: bind(runVxlanInnerL4DestinationPortChange),
    changeVxlanInnerL4DestinationPortCount: bind(runVxlanInnerL4DestinationPortCountChange),
    changeVxlanInnerL4DestinationPortMode: bind(runVxlanInnerL4DestinationPortModeChange),
    changeVxlanInnerL4DestinationPortStep: bind(runVxlanInnerL4DestinationPortStepChange),
    changeVxlanInnerL4SourcePort: bind(runVxlanInnerL4SourcePortChange),
    changeVxlanInnerL4SourcePortCount: bind(runVxlanInnerL4SourcePortCountChange),
    changeVxlanInnerL4SourcePortMode: bind(runVxlanInnerL4SourcePortModeChange),
    changeVxlanInnerL4SourcePortStep: bind(runVxlanInnerL4SourcePortStepChange),
    changeVxlanVni: bind(runVxlanVniChange),
    changeVxlanVniCount: bind(runVxlanVniCountChange),
    changeVxlanVniMode: bind(runVxlanVniModeChange),
    changeVxlanVniStep: bind(runVxlanVniStepChange)
  };
}
